################################################################################
# Node-RED Stack or Compose
################################################################################
# docker stack deploy node-red --compose-file docker-compose-node-red.yml
# docker-compose -f docker-compose-node-red.yml -p myNoderedProject up
################################################################################

# file edited based on the guide from "https://nodered.org/docs/getting-started/docker"
# as the repository "https://github.com/node-red/node-red-docker".
# Modification includes: adding more services, declaring dependencies between
#  container, build image to get custom flow and settings and packages.
version: "3.7"

# the list of container to start
services:
  node-red:
    build:
      context: ./Env-Node-Red
      dockerfile: Dockerfile
    environment:
      - TZ=Europe/Amsterdam
    depends_on:
      - mqtt-brocker
      - projettutoreservice
    restart: unless-stopped
    networks:
      - projet-net
    ports:
      - "1880:1880"
      #- "5455:1880"
    volumes:
      #Pour MAC:
      - ./Env-Node-Red:/data
      #Pour Windows:
      #- .\:/data


  mqtt-brocker:
    image: eclipse-mosquitto:1.6
    restart: unless-stopped
    networks:
      - projet-net
    ports:
      - "1883:1883"
      #- "5445:1883"

  projettutoreservice:
    image: node:12.18-alpine
    build:
      context: .
      dockerfile: ./Project Angular/projetTutore-server/Dockerfile
    environment:
      NODE_ENV: production
    depends_on:
      - mqtt-brocker
    restart: unless-stopped
    networks:
      - projet-net
    ports:
      - "3000:3000"
    volumes :
      - ./Project Angular/projetTutore-server:/usr/src/app


# Declare a couple volume that will outlive the VMs
volumes:
  projet-data: # bind the current folder as node-red-data
    driver_opts:
      type: none
      device: $PWD
      o: bind

# Declare the shared networks the container will used to interract
networks:
  projet-net:
